# Generated by Django 5.0.7 on 2024-08-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_user_alter_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='application',
            name='district',
        ),
    ]
